service: promodeAgro-admin-ecommerce-api

frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-offline
  - serverless-esbuild


custom:
  stage: ${opt:stage, 'dev'}
  esbuild:
    bundle: true
    minify: false

provider:
  name: aws
  stage: prod
  region: us-east-1
  runtime: nodejs18.x
  role: arn:aws:iam::851725323791:role/ecommerce_Lambda_Role
  versionFunctions: false
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "*"
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE
        
functions:
  - ${file(order/function.yml)}
  - ${file(inventory/function.yml)}
