service: promodeAgro-admin-ecommerce-api

frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  stage: prod
  region: us-east-1
  runtime: nodejs18.x
  role: arn:aws:iam::851725323791:role/ecommerce_Lambda_Role
  versionFunctions: false
  httpApi:   
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizer
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "*"
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE

functions:
  - ${file(inventory/function.yml)}
