get-items:
    handler: inventory/get-items.handler
    events:
      - httpApi:
          path: /inventory
          method: get
get-item:
    handler: inventory/get-item.handler
    events:
      - httpApi:
          path: /inventory/{id}
          method: get
getProductStats:
    handler: inventory/getProductStats.handler
    events:
      - httpApi:
          path: /getProductStats
          method: get

getItemOverview:
    handler: inventory/getItemOverview.handler
    events:
      - httpApi:
          path: /items/{productId}
          method: get
add-inventory:
    handler: inventory/add-item.handler
    events:
      - httpApi:
          path: /inventory
          method: post
publish-item:
    handler: inventory/publish-item.handler
    events:
      - httpApi:
          path: /publish/{id}
          method: put
update-item-status:
    handler: inventory/update-item-status.handler
    events:
      - httpApi:
          path: /inventory/status
          method: put


          