addProduct:
    handler: inventory/addProduct.handler
    events:
      - httpApi:
          path: /product
          method: post

getAllProduct:
    handler: inventory/getAllProducts.getAllInventory
    events:
      - httpApi:
          path: /getAllProducts
          method: get

getProductStats:
    handler: inventory/getProductStats.handler
    events:
      - httpApi:
          path: /getProductStats
          method: get

getItemOverview:
    handler: inventory/getItemOverview.handler
    events:
      - httpApi:
          path: /items/{productId}
          method: get
addInventory:
    handler: inventory/add-inventory.handler
    events:
      - httpApi:
          path: /inventory
          method: post
